### PR TITLE
feat: add gnuplot snippet

### PR DESCRIPTION
**Pull request by sanjayankur31**
Adds a snippet about how to quickly plot on the command line using GNUPlot.

### CODE REVIEW

**Review by mstimberg — COMMENTED** [review]
Great, thanks!

A minor nitpick: I think
````
```bash
$ ...
```
````
should be
````
```console
$ ....
```
````
otherwise, the numbers at the start of the lines get highlighted in a confusing way. Somewhere between sphinx/pygments/myst/… the proper highlighting with a different color for the `$` gets lost – it looks fine in the PDF, though :man_shrugging: 

I also wonder, whether we should do something about the long lines that get cut off – would line continuation with `\` be helpful or confusing?

**Comment by sanjayankur31** [comment]
I've updated it to `console` and broken the long lines too. I think breaking them is fine---the commands here aren't that complex so it's kind of obvious what is being done.

**Review by mstimberg — APPROVED** [review]
LGTM!

**Comment by mstimberg** [comment]
@all-contributors please add @mstimberg for review

**Pull request merged**
